### ISSUE TITLE
Custom Fonts (Google Fonts) in Customizing

### ISSUE THREAD

**Issue by MajorTomDE** [prtksxna/zuari#108]
Hey,

it would be great if you can implement a function within the customizing to easy change the font families.

Otherwise your theme is really great. I love the simple design.

Greating from Germany.
Tom

**Comment by prtksxna** [comment]
I am glad you like the theme 😊

Allowing Google fonts was on of the first things that I wanted to do in the theme (actually second — #2) but I just haven't gotten around to doing it yet.

I'll close this issue (since its a duplicate of #2) and encourage you to subscribe to that one to get an update.

**Comment by MajorTomDE** [comment]
Great! Thanks. I did not seen #2
